version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: unilab-api
    container_name: unilab-api
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - storage-data:/var/www/html/storage
    networks:
      - laravel-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=unilab_unilab-api
      - DB_USERNAME=unilab_unilab-api
      - DB_PASSWORD=secret

      - DB_LOCAL_DRIVER=pgsql
      - DB_LOCAL_HOST=db
      - DB_LOCAL_PORT=5432
      - DB_LOCAL_DATABASE=unilab_unilab-api
      - DB_LOCAL_USERNAME=unilab_unilab-api
      - DB_LOCAL_PASSWORD=secret

      - DB_SIGAA_DRIVER=pgsql
      - DB_SIGAA_HOST=db
      - DB_SIGAA_PORT=5432
      - DB_SIGAA_DATABASE=unilab_unilab-api
      - DB_SIGAA_USERNAME=unilab_unilab-api
      - DB_SIGAA_PASSWORD=secret

      - DB_SISTEMAS_COMUM_DRIVER=pgsql
      - DB_SISTEMAS_COMUM_HOST=db
      - DB_SISTEMAS_COMUM_PORT=5432
      - DB_SISTEMAS_COMUM_DATABASE=unilab_unilab-api
      - DB_SISTEMAS_COMUM_USERNAME=unilab_unilab-api
      - DB_SISTEMAS_COMUM_PASSWORD=secret


  db:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5435"
    environment:
      POSTGRES_DB: unilab_unilab-api
      POSTGRES_USER: unilab_unilab-api
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - laravel-network

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "8081:80"
  #   networks:
  #     - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  postgres-data:
  storage-data: